[build]
  publish = "public"
  command = "hugo --gc --minify"
  node_version = "18.16.0"  # Specify your desired Node.js version here

[context.production.environment]
  HUGO_VERSION = "0.138.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18.16.0"  # Specify Node.js version here

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.138.0"
  HUGO_ENV = "production"
  NODE_VERSION = "18.16.0"  # Specify Node.js version here

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.138.0"
  NODE_VERSION = "18.16.0"  # Specify Node.js version here

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.138.0"
  NODE_VERSION = "18.16.0"  # Specify Node.js version here

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18.16.0"  # Specify Node.js version here

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200
